#!/usr/bin/expect -f

set timeout 100
spawn telnet [lrange $argv 0 0 ]
match_max 100000
expect "login: "
send -- "[lrange $argv 1 1]\r"
expect "Password: "
send -- "[lrange $argv 2 2]\r"
expect "N7010#"
send "term len 0\n"
expect "N7010#"
send "show ip arp vrf all\n"
expect "N7010#"
send -- "exit\r"
expect eof

